<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1517534334238" stop="1517534334271">
  <name>test_001</name>
  <labels/>
  <test-cases>
    <test-case start="1517534334238" status="failed" stop="1517534334271">
      <name>Test_Abc.test_al</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_001.Test_Abc object at 0x000002A2DCE997F0&gt;

    def test_al(self):
&gt;       assert 0
E       assert 0

test_001.py:8: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="11608-MainThread"/>
        <label name="host" value="DESKTOP-2FT69H5"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
